SELECT *
FROM COVIDDEATH
ORDER BY 3,4

SELECT LOCATION,DATE,TOTAL_CASES, TOTAL_DEATHS, POPULATION
FROM COVIDDEATH
ORDER BY 1,2

--LOOKING FOR TOTAL DEATH VS TOTAL CASES
 
SELECT LOCATION,DATE,TOTAL_CASES, TOTAL_DEATHS, (TOTAL_DEATHS/TOTAL_CASES)*100 'PERCENTAGE OF DEATH'
FROM COVIDDEATH
WHERE TOTAL_CASES >0 AND DATE LIKE '2024-08%' AND LOCATION LIKE 'UNITED ST%'
ORDER BY 1,2

--LOOKING FOR POPULATION VS TOTAL CASES

SELECT LOCATION,DATE,TOTAL_CASES, TOTAL_DEATHS, POPULATION, (TOTAL_CASES/POPULATION)*100 'PERCENTAGE OF CASES'
FROM COVIDDEATH
ORDER BY 1,2

--COUNTRIES WITH HIGHEST INFECTION RATE COMPARED TO POPULATION

SELECT LOCATION,POPULATION, MAX(TOTAL_CASES) AS 'HIGHEST INFECTION COUNT', MAX(TOTAL_CASES/POPULATION)*100 'HIGHEST PERCENT POPULATION'
FROM COVIDDEATH
GROUP BY LOCATION, POPULATION
ORDER BY 4 DESC

--COUNTRIES WITH THE HIGHEST DEATH COUNT PER POPULATION

SELECT LOCATION, MAX(TOTAL_DEATHS ) AS 'HIGHEST DEATH COUNT'
FROM COVIDDEATH
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION
ORDER BY 2 DESC

SELECT LOCATION, MAX(CAST(TOTAL_DEATHS AS INT)) AS 'HIGHEST DEATH COUNT'
FROM COVIDDEATH
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION
ORDER BY 2 DESC

--LETS BREAK THIMGS DOWN BY CONTINENT
--CONTINENT WITH THE HIGHEST DEATH COUNT PER POPULATION

SELECT CONTINENT, MAX(TOTAL_DEATHS ) AS 'HIGHEST DEATH COUNT'
FROM COVIDDEATH
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT
ORDER BY 2 DESC

SELECT LOCATION, MAX(CAST(TOTAL_DEATHS AS INT)) AS 'HIGHEST DEATH COUNT'
FROM COVIDDEATH
WHERE CONTINENT IS NULL AND LOCATION <> 'WORLD' AND LOCATION <>'EUROPEAN UNION (27)'
GROUP BY LOCATION
ORDER BY 2 DESC

--GLOBAL NUMBERS


SELECT DATE, SUM(NEW_CASES) 'NEW CASES'
FROM COVIDDEATH
GROUP BY DATE
ORDER BY 2 DESC

SELECT DATE, SUM(NEW_CASES) 'TOTAL CASES', SUM(NEW_DEATHS)'TOTAL DEATHS'
FROM COVIDDEATH
GROUP BY DATE
ORDER BY 2 DESC

SELECT DATE, SUM(NEW_CASES) 'TOTAL CASES', SUM(NEW_DEATHS)'TOTAL DEATHS', (SUM(NEW_DEATHS)/SUM(NEW_CASES))*100 PERCENTDEATH
FROM COVIDDEATH
GROUP BY DATE
HAVING SUM(NEW_CASES)>0
ORDER BY 4 DESC


SELECT SUM(NEW_CASES) 'TOTAL CASES', SUM(NEW_DEATHS)'TOTAL DEATHS', (SUM(NEW_DEATHS)/SUM(NEW_CASES))*100 PERCENTDEATH
FROM COVIDDEATH
HAVING SUM(NEW_CASES)>0


SELECT * 
FROM COVIDVACCINATION VAC JOIN COVIDDEATH DEA ON VAC.location =DEA.location AND VAC.DATE = DEA. DATE

-- LOOKING FOR HOW MANY PEOPLE GOT VACCINATED

SELECT DEA.continent,DEA.LOCATION, DEA.DATE,  POPULATION, new_vaccinations
FROM COVIDVACCINATION VAC JOIN COVIDDEATH DEA ON VAC.location =DEA.location AND VAC.DATE = DEA. DATE
WHERE DEA.CONTINENT IS NOT NULL
ORDER BY 1,2,3

 SELECT DEA.continent,DEA.LOCATION, DEA.DATE,  POPULATION, new_vaccinations,  sum(CONVERT(BIGINT, new_vaccinations) ) 
 over (partition by dea.location ORDER BY DEA.DATE) 'ROLLING PEOPLE VACCINATED'
FROM COVIDVACCINATION VAC JOIN COVIDDEATH DEA ON VAC.location =DEA.location AND VAC.DATE = DEA. DATE
WHERE DEA.CONTINENT IS NOT NULL
ORDER BY 1,2,3
 
 --USE CTE

 WITH PERVER (CONTINENT, LOCATION, DATE, POPULATION, NEW_VACCINATIONS, ROLLINGPEOPLEVACCINATED) AS (SELECT DEA.continent,DEA.LOCATION, DEA.DATE,  POPULATION, new_vaccinations,  sum(CONVERT(BIGINT, new_vaccinations) ) 
 over (partition by dea.location ORDER BY DEA.DATE) 'ROLLING PEOPLE VACCINATED'
FROM COVIDVACCINATION VAC JOIN COVIDDEATH DEA ON VAC.location =DEA.location AND VAC.DATE = DEA. DATE
WHERE DEA.CONTINENT IS NOT NULL)
--ORDER BY 1,2,3)

SELECT*, (ROLLINGPEOPLEVACCINATED/POPULATION)*100 AS PERCENTPEOPLEVACCINATED
FROM PERVER

--TEMP TABLE

DROP TABLE IF EXISTS #vaccinationsdata
CREATE TABLE #vaccinationsdata
 (CONTENT NVARCHAR (255), LOCATION NVARCHAR (255) , DATE NVARCHAR (255), POPULATION NUMERIC, NEW_VACCINATIONS NUMERIC, ROLLINGPEOPLEVACCINATED NUMERIC)
  
  INSERT INTO #vaccinationsdata
 SELECT DEA.continent,DEA.LOCATION, DEA.DATE,  POPULATION, new_vaccinations, sum(CONVERT(BIGINT, new_vaccinations) ) 
 over (partition by dea.location ORDER BY DEA.DATE) 'ROLLING PEOPLE VACCINATED'
FROM COVIDVACCINATION VAC JOIN COVIDDEATH DEA ON VAC.location =DEA.location AND VAC.DATE = DEA. DATE
WHERE DEA.CONTINENT IS NOT NULL
--ORDER BY 1,2,3)

SELECT*, (ROLLINGPEOPLEVACCINATED/POPULATION)*100 AS PERCENTPEOPLEVACCINATED
FROM #vaccinationsdata
 
 --CREATING VIEW TO STORE DATA FOR DATA VISUALIZATION 

 CREATE VIEW PERCENTPOPULATIONVACCINATED AS
 SELECT DEA.continent,DEA.LOCATION, DEA.DATE,  POPULATION, new_vaccinations, sum(CONVERT(BIGINT, new_vaccinations) ) 
 over (partition by dea.location ORDER BY DEA.DATE) 'ROLLING PEOPLE VACCINATED'
FROM COVIDVACCINATION VAC JOIN COVIDDEATH DEA ON VAC.location =DEA.location AND VAC.DATE = DEA. DATE
WHERE DEA.CONTINENT IS NOT NULL


select *
from PERCENTPOPULATIONVACCINATED







